# Generated by Django 6.0.4 on 2026-04-10 13:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_url', models.URLField(blank=True, default='', max_length=500)),
                ('payload', models.JSONField(help_text='Raw response body from the source, stored for replay/debugging.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'raw_responses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(db_index=True, max_length=100)),
                ('rate_type', models.CharField(choices=[('savings_1yr_fixed', 'Savings 1-Year Fixed'), ('savings_easy_access', 'Savings Easy Access'), ('30yr_fixed_mortgage', '30-Year Fixed Mortgage'), ('15yr_fixed_mortgage', '15-Year Fixed Mortgage'), ('5yr_arm_mortgage', '5-Year ARM Mortgage')], db_index=True, max_length=50)),
                ('rate_value', models.DecimalField(decimal_places=4, max_digits=7)),
                ('effective_date', models.DateField(db_index=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('source_url', models.URLField(blank=True, default='', max_length=500)),
                ('ingested_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('raw_response', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rates', to='rates.rawresponse')),
            ],
            options={
                'db_table': 'rates',
                'ordering': ['-effective_date', '-ingested_at'],
                'indexes': [models.Index(fields=['provider', 'rate_type', '-effective_date'], name='idx_provider_type_date_desc'), models.Index(fields=['rate_type', '-effective_date'], name='idx_type_date_desc'), models.Index(fields=['-ingested_at'], name='idx_ingested_at_desc')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'rate_type', 'effective_date'), name='uq_provider_type_date')],
            },
        ),
    ]
